### ISSUE TITLE
I need to be transitioned out.

### ISSUE THREAD

**Issue by freialobo** [TechAtNYU/marketing#1]
Happy to work with whoever can do newsletter next (Bryant? let me know) but don't have time anymore.

**Comment by grungerabbit** [comment]
I think all were interested (Jordan, Bryant, Raghav)

How do you want to be transitioned out?

**Comment by freialobo** [comment]
Up to y'all! I can proofread the next 1-3 newsletters as needed. I have confidence in any of you to do it either way.

**Comment by grungerabbit** [comment]
I think it makes sense to do some kind of exit interview / tutorial thing, what do y'all think?

**Comment by freialobo** [comment]
sure. right before and after the meeting is good for me i can do it next week.
