### ISSUE TITLE
Who handles this for After Hours?

### ISSUE THREAD

**Issue by freialobo** [TechAtNYU/marketing#2]
Since we decided not to have a lead, who handles marketing briefs and such for After Hours? cc @terriburns

**Comment by terriburns** [comment]
the person who does it for that week. we can just remind them the week before.

**Comment by freialobo** [comment]
although, isn't the marketing brief for after hours the same every week? what do you think @grungerabbit

**Comment by grungerabbit** [comment]
i put in all of the AH this semester into the API this morning. marketing just needs to go in every week to the intranet and make a fb event.

**Comment by terriburns** [comment]
:+1:

**Comment by freialobo** [comment]
awesome - who would be the point person for that?

**Comment by grungerabbit** [comment]
for making the fb event? does this really matter to know RIGHT NOW? it takes 5 minutes to do. 

i trust that jordan will allocate it properly amongst his team. i will talk to him and make sure AH is accounted for; mkting can come up with the proper strategy (aka how much time in advance to make the fb, who does the collab fund monies form, etc)

you can also join #mkting slack to discuss this

**Comment by terriburns** [comment]
we can table this discussion to the eboard meeting on tues, if that would be easier.

**Comment by freialobo** [comment]
sounds good :)
